jwt:
  secret: "123456"
  access_expiry: 2
  refresh_expiry: 720

app:
  env: "development"
  http_addr: ":8080"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

mysql:
  dsn: "root:123456@tcp(localhost:3306)/im_system?charset=utf8mb4&parseTime=True&loc=Local"

ws:
  allowed_origins: []

presence:
  ttl: "90s"
  heartbeat_interval: "30s"
