basePath: /
definitions:
  github_com_zyy125_im-system_internal_handler_dto.UserLoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  github_com_zyy125_im-system_internal_handler_dto.UserRegisterReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  github_com_zyy125_im-system_pkg_response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a IM System API.
  title: IM System API
  version: "1.0"
paths:
  /api/users/auth/logout:
    post:
      consumes:
      - application/json
      description: 用户登出，将JWT token加入黑名单
      produces:
      - application/json
      responses:
        "200":
          description: 登出成功
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
        "400":
          description: 参数校验错误
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
      security:
      - BearerAuth: []
      summary: 用户登出
      tags:
      - 用户
  /api/users/login:
    post:
      consumes:
      - application/json
      description: 用户登录，返回JWT token
      parameters:
      - description: 用户登录请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/github_com_zyy125_im-system_internal_handler_dto.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
        "400":
          description: 参数校验错误
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
      summary: 用户登录
      tags:
      - 用户
  /api/users/register:
    post:
      consumes:
      - application/json
      description: 用户注册，返回JWT token
      parameters:
      - description: 用户注册请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/github_com_zyy125_im-system_internal_handler_dto.UserRegisterReq'
      produces:
      - application/json
      responses:
        "201":
          description: 注册成功
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
        "400":
          description: 参数校验错误
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/github_com_zyy125_im-system_pkg_response.Response'
      summary: 用户注册
      tags:
      - 用户
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
